- charts/hedera-network/templates/_helpers.tpl
- charts/hedera-network/templates/proxy/envoy-deployment.yaml
- add the fix so that haproxy and envoy-proxy uses the default image tag instead of using Chart.AppVersion
- Closes #264
> fix: default tag is not set properly for proxy containers

- charts/hedera-network/config-files/envoy.yaml
- charts/hedera-network/templates/services/envoy-svc.yaml
- charts/hedera-network/templates/services/haproxy-svc.yaml
- charts/hedera-network/values.yaml
- update envoy cluster name from echo_service to non_tls_grpc_cluster
- add HAProxy and Envoy service definitions with support for both ClusterIP and LoadBalancer configurations
- Closes #225
> feat: add service definitions for HAProxy and Envoy with support for both ClusterIP and LoadBalancer configurations

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/zxc-code-analysis.yaml
- .github/workflows/zxc-compile-code.yaml
- .github/workflows/zxc-release-maven-central.yaml
- .github/workflows/zxf-snyk-monitor.yaml
- buildSrc/src/main/kotlin/com/hedera/fullstack/gradle/helm/release/HelmArtifactTask.kt
- charts/hedera-network/Chart.yaml
- Updates the default Helm CLI version used by both the Gradle plugin and by the CI pipelines.
- Adds version number comments to the end of each and every third-party Github Actions step uses line.
- Adds general comments to the CI pipelines where additional clarity is needed.
- Closes #282
> chore: update CI workflow definitions with version numbers and comments for clarity

- buildSrc/src/main/kotlin/Utils.kt
- Fixes the subchart version mangling caused by the `versionAsSpecified` tasks incorrectly ignoring leading whitespace when updating the chart versions.
- Closes #284
> fix: resolves the accidental mangling of Helm subchart versions on release

- charts/hedera-network/config-files/otel-collector-config.yaml
- charts/hedera-network/templates/services/network-node-svc.yaml
- charts/hedera-network/templates/sidecars/_otel-collector.tpl
- charts/hedera-network/templates/telemetry/prometheus-svc-monitor.yaml
- charts/hedera-network/values.yaml
- dev/scripts/telemetry.sh
- dev/telemetry/prometheus/prometheus.yaml
- Update Open Telemetry configuration to support optional remote write pushing of metrics and log
- add prometheus 8889 port for scraping
- fix /etc/otelcol-contrib/config.yaml mount for otel collector
- fix telemetry.sh kubectl wait syntax
- Closes #226
> feat: update Open Telemetry configuration to support optional remote write pushing of metrics and log

- fullstack-helm-client/src/main/java/module-info.java
- fullstack-helm-client/src/test/java/module-info.java
- converts helm client test source set to a module
- Closes #258
> feat: convert helm client test source set to a module

- charts/hedera-network/templates/rbac/pod-monitor-role.yaml
- allows pod-monitor-role to have access to secrets
- Closes #308
> feat: allow pod-monitor-role to have access to secrets

- .github/workflows/zxc-compile-code.yaml
- dev/Makefile
- dev/ci/ci-values.yaml
- dev/scripts/docker.sh
- dev/scripts/main.sh
- dev/scripts/telemetry.sh
- Enable building kubectl-bats docker image locally or in CI pipeline for helm tests
- Restructure build scripts
- Closes #307
> feat: enable locally building and loading kubectl-bats docker image into the cluster for helm tests

- charts/hedera-network/templates/services/haproxy-svc.yaml
- charts/hedera-network/templates/services/network-node-svc.yaml
- charts/hedera-network/templates/telemetry/prometheus-svc-monitor.yaml
- Expose prometheus metrics from HAProxy
- Allows prometheus service monitor to scrape both network-node and HAProxy metrics based on a specific label `fullstack.hedera.com/prometheus-endpoint: active`
- The label also allows disabling prometheus service monitor scraping
- Ensures `/stats` (requires login) and `/metrics` endpoints are available for HAProxy
- Closes #269
- HAProxy stats: /stats
- HAProxy metrics: /metrics 
- Prometheus targets:
- Exported HAProxy metrics:
> feat: expose prometheus metrics from HAProxy

- charts/hedera-network/templates/gateway-api/envoy-grpc-web-routes.yaml
- charts/hedera-network/templates/gateway-api/gateway.yaml
- charts/hedera-network/templates/gateway-api/haproxy-grpc-routes.yaml
- charts/hedera-network/templates/gateway-api/network-node-grpc-routes.yaml
- Support Higher Number of Nodes With Consistent Gateway Port Mapping
```
Gossip ports:   node0: 51000 ... node999: 51999  (Node Port 50111)
GRPC ports:     node0: 52000 ... node999: 52999  (Node Port 50211)
GRPCS ports:    node0: 53000 ... node999: 53999  (Node Port 50212)
GRPC-Web ports: node0: 18000 ... node999: 18999  (Node Port 8080)
```
- Closes #334
> feat: support higher number of nodes with consistent gateway port mapping

- .github/workflows/flow-deploy-release-artifact.yaml
- Locks the semantic release CLI toolchain to specific versions in order to resolve the failures encountered during the `v0.8.0` release.
- Closes #341
> fix: lock the semantic release toolchain to specific known working versions

- fullstack-base-api/src/main/java/com/hedera/fullstack/base/api/collections/KeyValuePair.java
- fullstack-base-api/src/test/java/com/hedera/fullstack/base/api/test/collections/KeyValuePairTest.java
- updates the KeyValuePair.equals() method to only compare key (not value)
- Closes #346
> fix: update KeyValuePair.equals to only compare key (not value)

- dev/scripts/gateway.sh
- updated `destroy-gateway-api` command to remove `gateway-system` namespace as well
- Closes #349
> fix: uninstall envoy-gateway should also remove gateway-system namespace that it created

- build-logic/project-plugins/build.gradle.kts
- upgrade to org.gradlex:java-module-dependencies:1.4.1
- Closes #364 
- relates to #304
> feat: upgrade to org.gradlex:java-module-dependencies:1.4.1

- .github/workflows/zxc-compile-code.yaml
- charts/hedera-network/Chart.lock
- charts/hedera-network/Chart.yaml
- charts/hedera-network/templates/network-node-statefulset.yaml
- charts/hedera-network/templates/pdb.yaml
- charts/hedera-network/templates/rbac/pod-monitor.yaml
- charts/hedera-network/tests/env.sh
- charts/hedera-network/tests/env.template
- charts/hedera-network/tests/run.sh
- charts/hedera-network/values.yaml
- dev/Makefile
- dev/dev-cluster.yaml
- dev/scripts/docker.sh
- dev/scripts/env.sh
- dev/scripts/gateway.sh
- dev/scripts/main.sh
- dev/scripts/telemetry.sh
- Add support for the following:
- podAnnotations
- podLabels
- nodeSelectors
- tolerations
- affinity
- priorityClass
- podDisruptionBudget
- Tidy up few makefile targets
- Add node annotation similar to GKE and also update CI pipeline as needed
- Add switches to disable dependent charts as needed
- Closes #344
> feat: add support for scheduling pods based on node labels, taints, and affinity

- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/execution/HelmExecution.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/execution/HelmExecutionBuilder.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/Chart.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/install/InstallChartOptions.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/install/InstallChartOptionsBuilder.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/resource/HelmSoftwareLoader.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/execution/HelmExecutionBuilderTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/execution/HelmExecutionTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/model/InstallChartOptionsBuilderTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/proxy/request/chart/ChartInstallRequestTest.java
- fullstack-service-locator/src/main/java/com/hedera/fullstack/service/locator/api/ArtifactLoader.java
- enhance Helm Install to support multiple set parameters
- enhance Helm Install to support multiple values parameters
- downgrade to traditional SLF4J methods to support Gradle's SLF4J 1.7 runtime
- improve HelmExecution.responseAs() HelmExecutionException
- improved HelmClientTest to reduce helm client commands and remove inconsistent test case failures
- improve test coverage for ChartInstallRequest.apply()
PR Walkthrough (13 minutes): https://www.loom.com/share/bff374ec190a44c3aadac2f787bf13f7?sid=7e32aad3-abde-4f7b-90d6-4ba22485edd7
- Closes #366
- relates to #304
> feat: enhance Helm Install to support multiple set and values parameters

- .github/workflows/zxc-compile-code.yaml
- build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.jpms-modules.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.root.gradle.kts
- build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.umbrella.gradle.kts
- build-logic/settings-plugins/build.gradle.kts
- build-logic/settings-plugins/src/main/kotlin/com.hedera.fullstack.settings.settings.gradle.kts
- build.gradle.kts
- fullstack-examples/build.gradle.kts
- fullstack-examples/settings.gradle.kts
- fullstack-gradle-plugin/build.gradle.kts
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/FullstackPlugin.java
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTask.java
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/package-info.java
- fullstack-gradle-plugin/src/main/java/module-info.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java
- fullstack-gradle-plugin/src/test/java/module-info.java
- settings.gradle.kts
- settings-plugins
- fullstack-examples becomes a separate gradle project in order to leverage the fullstack-gradle-plugin
- HelmInstallChartTask
- added example usages of HelmInstallChartTask in fullstack-examples project
Notes:
- fullstack-examples now has to be opened as a separate IntelliJ project in order for it to load in IntelliJ
- running fullstack-examples from the command line:
```
cd fullstack-examples
../gradlew clean build
../gradlew spotlessApply
../gradlew helmInstallNginxChart
helm uninstall nginx-release --namespace nginx-ns
```
PR Walkthrough (21 minutes): https://www.loom.com/share/01ec31f227af4b6c8debbdaa6f5faf49?sid=70205d86-fe5c-43db-98e9-cd6b1ec22007
- Relates to #288 
- Closes #322 
- depends on #365 
- depends on #366
> feat: add helm execution gradle task: HelmInstallChartTask

- fullstack-examples/build.gradle.kts
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmUninstallChartTask.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmUninstallChartTaskTest.java
- add HelmUninstallChartTask to fullstack-gradle-plugin
- add example usage in fullstack-examples/build.gradle.kts
PR Walkthrough (2 minutes): https://www.loom.com/share/a4742de2d0f74e5bb9c4d47caf19866e?sid=c2e55ba2-6bdd-44d3-ab83-fe9d191a3e23
- Closes #323 
- depends on #288
> feat: add helm execution gradle task: HelmUninstallChartTask

- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/HelmClient.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/impl/DefaultHelmClient.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/test/TestChartOptions.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/test/TestChartOptionsBuilder.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/proxy/request/chart/ChartTestRequest.java
- fullstack-helm-client/src/main/java/module-info.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/model/TestChartOptionsBuilderTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/proxy/request/chart/ChartTestRequestTest.java
- adds the helm test subcommand with filter and timeout options
PR Walkthrough (4 minutes): https://www.loom.com/share/3c18ac66fa4047f1ba25dfab7903b3eb?sid=3e98559a-b6cd-478d-bac3-bffb100c0edf
- Closes #305 
- depends on #375
> feat: add helm test subcommand with options

- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/HelmClient.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/HelmClientBuilder.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/impl/DefaultHelmClient.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/impl/DefaultHelmClientBuilder.java
- fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/proxy/request/chart/ChartDependencyUpdateRequest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java
- fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/proxy/request/chart/ChartDependencyUpdateRequestTest.java
- adds the helm dependency update subcommand 
- add ability to specify working directory into helm client and its builder
PR Walkthrough (4 minutes): https://www.loom.com/share/239d457b687b4ffdaf18037dd3c77161?sid=d38361c3-8b79-4ba8-9d22-2c3d394d696f
- Closes #306 
- depends on #305
> feat: add helm dependency update subcommand

- fullstack-examples/build.gradle.kts
- fullstack-gradle-plugin/build.gradle.kts
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmListReleasesTask.java
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmReleaseExistsTask.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmReleaseExistsTaskTest.java
- adds a gradle task for checking if the Helm release specified is present, if it is not, it will fail.
This will be used to replace the following in the makefile sunset:
```
.PHONY: is-minio-operator-installed
is-minio-operator-installed:
@echo ">> Checking for minio operator..."; \
helm list --namespace=minio-operator | grep minio-operator &> /dev/null && { echo "Found minio operator."; exit 0; }; \
echo "Minio operator not found."; exit 1
```
- Closes #326
> feat: add gradle Helm release exists task

- charts/hedera-network/templates/network-node-statefulset.yaml
- charts/hedera-network/templates/proxy/envoy-deployment.yaml
- charts/hedera-network/templates/proxy/haproxy-deployment.yaml
- charts/hedera-network/templates/tests/test-deployment.yaml
- charts/hedera-network/values.yaml
- dev/Makefile
- dev/dev-cluster.yaml
- dev/scripts/main.sh
- add `nodeSelector` and `tolerations` for all pods in the chart and dependent charts
- disable redundant mirror-node containers
- Closes #373
Some of the dependent charts do not support passing `nodeSelector` and `tolerations`. For example `rest-monitor` in hedera-mirror-node chart. See comment: https://github.com/hashgraph/full-stack-testing/issues/373#issuecomment-1747935956
I have disabled those redundant containers.
> feat: apply nodeSelector and tolerations to all pods including proxies

- fullstack-examples/build.gradle.kts
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmUninstallChartTask.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmUninstallChartTaskTest.java
- add ifExists option to Gradle Helm uninstall task
Note: this will help replace the existing makefile code such as:
```
local count=$(helm list -q -n "${NAMESPACE}" | grep -c "${HELM_RELEASE_NAME}")
if [[ $count -ne 0 ]]; then
echo "Uninstalling helm chart ${HELM_RELEASE_NAME} in namespace ${NAMESPACE}... "
echo "-----------------------------------------------------------------------------------------------------"
helm uninstall -n "${NAMESPACE}" "${HELM_RELEASE_NAME}"
sleep 10
echo "Uninstalled helm chart ${HELM_RELEASE_NAME} in namespace ${NAMESPACE}"
else
echo "Helm chart '${HELM_RELEASE_NAME}' not found in namespace ${NAMESPACE}. Nothing to uninstall. "
fi
```
- Closes #391
> feat: add ifExists option to Gradle Helm uninstall task

- fullstack-examples/build.gradle.kts
- fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmDependencyUpdateTask.java
- fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmDependencyUpdateTaskTest.java
- adds the Gradle Helm dependency update task
- Closes #324
> feat: add gradle Helm dependency update task 

- charts/hedera-network/charts/hedera-explorer/.helmignore
- charts/hedera-network/charts/hedera-explorer/templates/configmap.yaml
- charts/hedera-network/charts/hedera-explorer/values.yaml
- fix: store hedera-explorer chart as dependency until next official version is released
This is to store [this](https://github.com/hashgraph/hedera-mirror-node-explorer/commit/7ba2721c3796403bb7d142df697ba3f2a7d68bff) change in our repo.
- Closes #434
> fix: store hedera-explorer chart as dependency until next official version is released

- fullstack-network-manager/resources/dev-cluster.yaml
- fullstack-network-manager/src/commands/base.mjs
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/commands/init.mjs
- fullstack-network-manager/src/core/constants.mjs
- fullstack-network-manager/src/core/logging.mjs
- fullstack-network-manager/src/index.mjs
- implemented the following commands
- `cluster create` 
- `cluster delete`
- `cluster list`
- `cluster info`
- create a custom logger and use colored messages
- polish up previously implemented `init` command to show status message to user
Note that the default cluster name is `fst-<USER>`. For example, on my machine it was defaulted to `fst-leninmehedy`
```
➜  fsnetman cluster create -h
fsnetman cluster create
Create a cluster
Options:
-n, --name     Name of the cluster       [string] [default: "fst-leninmehedy"]
-h, --help     Show help                                             [boolean]
-v, --version  Show version number                                   [boolean]
➜  fsnetman cluster info -h
fsnetman cluster info
Get cluster info
Options:
-n, …
```
> feat(cli): implement cluster create and delete commands

- charts/fullstack-cluster-setup/Chart.lock
- charts/fullstack-cluster-setup/Chart.yaml
- charts/fullstack-cluster-setup/values.yaml
- dev/Makefile
- dev/scripts/env.sh
- dev/scripts/main.sh
- dev/temp/.gitignore
- add minio operator to fullstack-cluster-setup chart
- update makefile and supporting scripts to remove individual helm install of minio operator and instead enable it in the fullstack-cluster-setup chart
- Closes #398
> feat: add minio operator to fullstack-cluster-setup chart

- charts/fullstack-deployment/templates/gateway-api/gateway.yaml
- charts/fullstack-deployment/templates/gateway-api/hedera-explorer-route.yaml
- charts/fullstack-deployment/values.yaml
- dev/gateway-api/Makefile
- dev/scripts/gateway.sh
- Add Gateway route for Hedera Explorer
- Closes #340
> feat: add Gateway API route for Hedera Explorer

- fullstack-network-manager/src/commands/base.mjs
- fullstack-network-manager/src/commands/chart.mjs
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/core/helm.mjs
- fullstack-network-manager/src/core/index.mjs
- fullstack-network-manager/src/core/kubectl.mjs
- fullstack-network-manager/src/core/logging.mjs
- fullstack-network-manager/src/core/shell_runner.mjs
- fullstack-network-manager/src/index.mjs
- fullstack-network-manager/test/commands/base.test.js
- fullstack-network-manager/test/commands/init.test.js
- encapsulate helm and kubectl commands
- polish `cluster` commands
- polish `chart` commands
- apply colors in console messages for clarity
- Closes #469
> fix(cli): encapsulate helm and kubectl commands and code cleanup

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/flow-pull-request-checks.yaml
- .releaserc
- build-logic/project-plugins/src/main/kotlin/Utils.kt
- build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.aggregate-reports.gradle.kts
- fullstack-network-manager/.npmrc
- fullstack-network-manager/README.md
- fullstack-network-manager/package.json
- publish cli to Github NPM package registry
- update semantic-release config to include `package.json` from CLI with updated version
- update semantic-release config to include `Chart.yaml` from `fullstack-cluster-setup` with updated version
- added some debug logic for CI pipeline
- allow `ci/*` branches to be used to dry-run semantic release process for debugging
Attempted to dry-run [here](https://github.com/hashgraph/full-stack-testing/actions/runs/6699421036/job/18203532543)
- Closes #444
> chore(ci): publish CLI to Github NPM package registry

- charts/fullstack-cluster-setup/values.yaml
- fullstack-network-manager/README.md
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/commands/flags.mjs
- set fullstack-cluster-setup to default true in fsnetman for installing minio & prometheus-stack
- Closes #475
NOTE: for #475 to work without any additional commands, #473 needs to be closed.
> bug: set fullstack-cluster-setup to default true in fsnetman for installing minio & prometheus-stack

- .github/workflows/flow-deploy-release-artifact.yaml
- .releaserc
- fullstack-network-manager/.npmrc
- Adds support for publishing helm charts to github pages
- Streamlines NPM package releases by using the `@semantic-release/npm`  plugin
- Closes #459
> chore: add support for publishing helm chart to github pages

- .github/workflows/flow-deploy-release-artifact.yaml
- fix permission issue in [flow-deploy-release-artifact.yaml](https://github.com/hashgraph/full-stack-testing/compare/bug-wf-break?expand=1#diff-f1bcd1ef387efde297c1469d5f2c6ed7ba81f38b14e3d54d270914d1125bb2cc)
- Closes #
> bug: add permission required to run maven publish workflow

- charts/fullstack-cluster-setup/Chart.lock
- charts/fullstack-cluster-setup/Chart.yaml
- charts/fullstack-cluster-setup/values.yaml
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/commands/flags.mjs
- fullstack-network-manager/src/index.mjs
- add cert-manager subchart to fullstack-cluster-setup Helm chart
- Closes #487
> feat: add cert-manager subchart to fullstack-cluster-setup Helm chart

- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/core/kubectl.mjs
- set namespace to kubectl context after cluster create
- Closes #519
> fix: set namespace to kubectl context after cluster create

- fullstack-network-manager/src/commands/base.mjs
- In `fstnetman init` dependency check should make use of `kubectl version --client`,
without this if a k8s server in default context is not reachable it fails with an error
and falsely reports that 'kubectl' is not found
- Closes #530
> fix(cli): kubectl version command errors out if server is un reachable

- dev/scripts/helper.sh
- fix variable name to check platform version
- Closes #502
> fix: use correct variable name to check platform version

- fullstack-network-manager/fsnetman.mjs
- Introduces a new environment variable 'DEV_MODE'
- If its false, then disable stack trace output on the console
- This leads to a cleaner UX experience for users
- Closes #541
> feat(cli) : adding a new environment variable DEV_MODE

- fullstack-network-manager/.eslintrc.yml
- fullstack-network-manager/fsnetman.mjs
- fullstack-network-manager/jest.config.mjs
- fullstack-network-manager/src/commands/base.mjs
- fullstack-network-manager/src/commands/chart.mjs
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/commands/flags.mjs
- fullstack-network-manager/src/commands/index.mjs
- fullstack-network-manager/src/commands/init.mjs
- fullstack-network-manager/src/commands/node.mjs
- fullstack-network-manager/src/core/chart_manager.mjs
- fullstack-network-manager/src/core/config_manager.mjs
- fullstack-network-manager/src/core/constants.mjs
- fullstack-network-manager/src/core/errors.mjs
- fullstack-network-manager/src/core/helm.mjs
- fullstack-network-manager/src/core/index.mjs
- fullstack-network-manager/src/core/kind.mjs
- fullstack-network-manager/src/core/kubectl.mjs
- fullstack-network-manager/src/core/logging.mjs
- fullstack-network-manager/src/core/package_downloader.mjs
- fullstack-network-manager/src/core/platform_installer.mjs
- fullstack-network-manager/src/core/shell_runner.mjs
- fullstack-network-manager/src/core/templates.mjs
- fullstack-network-manager/src/core/zippy.mjs
- fullstack-network-manager/src/index.mjs
- uses correct eslint config to inspect .mjs files
> Fix eslint configuration and fix lint issues

- .github/workflows/zxc-compile-code.yaml
- ruleset.xml
- disable UnnecessaryBlock check for ECMAScripts by Codacy
- Closes #556
> chore: disable Codacy PMD rule UnnecessaryBlock for ECMAScripts

- .github/workflows/zxc-compile-code.yaml
- charts/fullstack-deployment/templates/_helpers.tpl
- fullstack-network-manager/test/e2e/core/package_downloader_e2e.test.mjs
- fullstack-network-manager/test/e2e/core/platform_installer_e2e.test.mjs
- use quote for test labels to support empty values
- ci: use test-cache-dir to avoiding duplicate download of platform build.zip file
- Closes #532
> fix(chart): use quote for test labels and fix e2e tests 

- charts/fullstack-deployment/templates/configmaps/envoy-cm.yaml
- charts/fullstack-deployment/templates/configmaps/haproxy-cm.yaml
- charts/fullstack-deployment/templates/configmaps/otel-collector-cm.yaml
- charts/fullstack-deployment/templates/configmaps/test-cm.yaml
- Add testmetadata to configmaps
- Closes #570 
- Closes #409
> feat: add testmetadata to configmaps

- fullstack-network-manager/test/unit/core/errors.test.mjs
- Add tests for core/errors module
- Closes #546
> test(cli): add tests for core/errors module

- fullstack-core/fullstack-bom/build.gradle.kts
- fullstack-core/fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java
- fullstack-core/fullstack-service-locator/build.gradle.kts
- remove snyk scan issue by upgrading jcovalent
- bump helm client test timeout to 30 seconds to remove intermittent failures
- Closes #597 
- closes #533
> fix: remove snyk scan issue by upgrading jcovalent

- fullstack-core/fullstack-bom/build.gradle.kts
- settings.gradle.kts
- Updates to version `0.3.2` of the jcovalent library.
- Updates the Gradle enterprise plugin version.
- Removes the use of enforced platform.
- Updates to version `5.10.1` of the JUnit BOM.
- Closes #608
> chore: update jcovalent version and remove use of enforced platform

- fullstack-network-manager/test/unit/core/logging.test.mjs
- Add tests for core/logging module
- Closes #545
> test(cli): add tests for core/logging module

- fullstack-network-manager/test/unit/core/shell_runner.test.mjs
- Add tests for core/shell_runner module
- Closes #552
> test(cli): add tests for core/shell_runner module

- fullstack-network-manager/src/core/logging.mjs
- Remove syslog levels from core/logging
- Rename winsonLogger to winstonLogger in core/logging
- Closes #613
- Closes #614
> chore(cli): remove syslog levels and fix typo in core/logging module

- fullstack-network-manager/src/commands/chart.mjs
- fullstack-network-manager/src/commands/cluster.mjs
- fullstack-network-manager/src/commands/init.mjs
- fullstack-network-manager/src/commands/node.mjs
- fullstack-network-manager/src/commands/relay.mjs
- fullstack-network-manager/src/core/constants.mjs
- fullstack-network-manager/test/unit/core/shell_runner.test.mjs
- show elapsed time for each step
- Closes #619
> feat(cli): show elapsed time for each step

- .github/workflows/zxc-fsnetman-tests.yaml
- fullstack-network-manager/fsnetman.mjs
- fullstack-network-manager/src/commands/flags.mjs
- fullstack-network-manager/src/commands/index.mjs
- fullstack-network-manager/src/commands/node.mjs
- fullstack-network-manager/src/core/config_manager.mjs
- fullstack-network-manager/src/core/logging.mjs
- fullstack-network-manager/src/core/shell_runner.mjs
- fullstack-network-manager/src/index.mjs
- fullstack-network-manager/test/unit/core/shell_runner.test.mjs
- enable --dev flag for dev mode
- removed DEV_MODE env variable settings
- only show error stacktrace in console if `--dev` mode is enabled
- Closes #622
> fix(cli): enable --dev flag for dev mode

- charts/fullstack-deployment/charts/acme-cluster-issuer/templates/production.yaml
- charts/fullstack-deployment/charts/acme-cluster-issuer/templates/staging.yaml
- charts/fullstack-deployment/charts/acme-cluster-issuer/values.yaml
- charts/fullstack-deployment/charts/hedera-explorer/templates/ingress.yaml
- charts/fullstack-deployment/charts/hedera-explorer/values.yaml
- charts/fullstack-deployment/templates/cert-manager/certificate-requests.yaml
- charts/fullstack-deployment/templates/cert-manager/cluster-issuer.yaml
- charts/fullstack-deployment/templates/ingress/ingress-class.yaml
- charts/fullstack-deployment/values.yaml
- use Acme Lets Encrypt cluster issuer for TLS in Hedera Explorer
- Closes #631
> feat: use Acme Lets Encrypt cluster issuer for TLS in Hedera Explorer

- .github/workflows/flow-deploy-release-artifact.yaml
- docker/ubi8-init-java21/Dockerfile
- docker/ubi8-init-java21/build.gradle.kts
- docker/ubi8-init-java21/entrypoint.sh
- docker/ubi8-init-java21/network-node.service
- settings.gradle.kts
- Adds a new Docker definition for Java 21 support.
- Updates the CI workflow to release the new image.
- Adds a Gradle module descriptor for the image.
- Closes #701
> fix: add a docker image for Java 21 support

- .github/workflows/zxc-helm-chart-tests.yaml
- docker/ubi8-init-java21/entrypoint.sh
- solo/README.md
- solo/src/commands/cluster.mjs
- solo/src/commands/flags.mjs
- solo/src/commands/init.mjs
- solo/src/commands/network.mjs
- solo/src/commands/node.mjs
- solo/src/commands/prompts.mjs
- solo/src/core/config_manager.mjs
- solo/src/core/constants.mjs
- solo/src/core/helpers.mjs
- solo/src/core/logging.mjs
- solo/src/index.mjs
- solo/test/e2e/setup-e2e.sh
We can now just set the node IDs to deploy different number of network nodes, 
e.g. `solo network deploy -i node0,node1,node2,node3,node4......nodeN`
- allow deploying different number network nodes
- only output extra logs if `--dev` flag is set
- updated solo README with console output logs for reference
- Closes #582
> feat(cli): allow deploying different number network nodes

- charts/fullstack-deployment/config-files/otel-collector-config.yaml
- charts/fullstack-deployment/templates/cert-manager/certificate-requests.yaml
- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/templates/proxy/envoy-deployment.yaml
- charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
- charts/fullstack-deployment/templates/rbac/pod-monitor.yaml
- charts/fullstack-deployment/templates/services/envoy-svc.yaml
- charts/fullstack-deployment/templates/services/haproxy-svc.yaml
- charts/fullstack-deployment/values.yaml
- use boolean values instead of string literals for booleans
- Closes #479
> fix(chart): use boolean values instead of string literals for booleans

- solo/src/commands/network.mjs
- solo/test/e2e/commands/node.test.mjs
- assign node account ID correctly base on start account ID
- Closes #748
> fix(cli): assign node account ID correctly base on start account ID

- charts/fullstack-deployment/values.yaml
- `backup-uploader` is buggy as outline here: https://github.com/hashgraph/full-stack-testing/issues/745
- moreover, `backup-uploader` image is available only for amd64. As a result user is unable to deploy the chart in `microk8s cluster` or `aarch64 linux vm`
We shall enable it later once the correct image is available as tracked here: https://github.com/hashgraph/full-stack-testing/issues/747
- Closes #
> fix(chart): disable backup-uploader

- solo/src/commands/flags.mjs
- solo/src/core/config_manager.mjs
- solo/src/index.mjs
- solo/test/unit/core/config_manager.test.mjs
- fix: cluster-name in the config is not overwritten based on current kubernetes context
- fix: refactor config manager with each function having a single responsibility to avoid confusion
- fix: parsing different types of values (string, integer/float, boolean)
- test: add more unit tests
- Closes #
> fix(cli): refactor config manager with each function having a single responsibility to avoid confusion

- charts/fullstack-deployment/config-files/haproxy.cfg
- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/templates/services/haproxy-svc.yaml
- solo/src/commands/base.mjs
- solo/src/commands/flags.mjs
- solo/src/commands/node.mjs
- solo/src/commands/prompts.mjs
- solo/src/core/account_manager.mjs
- solo/src/core/constants.mjs
- solo/src/core/k8.mjs
- solo/src/core/templates.mjs
- solo/src/index.mjs
- solo/test/e2e/commands/node.test.mjs
- rekey special accounts at startup so they are not using genesis keys
- update haproxy.cfg to show more sysout to k8s logs
- added account-id labels to:
- `charts/fullstack-deployment/templates/network-node-statefulset.yaml`
- `charts/fullstack-deployment/templates/services/haproxy-svc.yaml`
- added sleep and check in `solo/src/commands/node.mjs.`.`checkNetworkNodePod` to support user calling the `solo node start` after it was previously already running
- refactored prompts.mjs to reduce duplication
- added new methods to `solo/src/core/k8.mjs`
- `getSecret()`
- `createSecret()`
- Closes #668
> feat: rekey special accounts at startup so they are not using genesis keys

- solo/README.md
- solo/src/core/dependency_manager.mjs
- solo/src/core/helpers.mjs
- solo/src/core/platform_installer.mjs
- solo/test/unit/core/dependency_manager.test.mjs
- solo/test/unit/core/helpers.test.mjs
- add a helper functions to parse and compare semver (MAJOR.MINOR.PATCH)
- do version check for dependencies
- lower the required helm version to match it with our CI pipeline
- Closes #508 
- Depends on: #753
> fix: do version check for dependencies

- solo/src/commands/cluster.mjs
- solo/src/commands/init.mjs
- solo/src/commands/network.mjs
- solo/src/commands/node.mjs
- solo/src/commands/relay.mjs
- solo/src/core/config_manager.mjs
- solo/test/e2e/commands/node.test.mjs
- solo/test/unit/core/config_manager.test.mjs
- use default values for all flags during init
- invoke configManager.update(argv) instead of configManager.load(argv)
- Closes #
> fix: use default values for all flags during init

- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- docker/ubi8-init-java17/Dockerfile
- docker/ubi8-init-java17/network-node.service
- docker/ubi8-init-java21/Dockerfile
- docker/ubi8-init-java21/network-node.service
- solo/src/core/platform_installer.mjs
- update Dockerfile for `ubi8-init-java17` and `ubi8-init-java21` images to put entrypoint.sh in `/opt/hgcapp/services-hedera/HapiApp2.0/`
- do not reset the directory `/opt/hgcapp/services-hedera/HapiApp2.0/` during node setup anymore (as otherwise it would delete the entrypoint.sh)
- update `setupHapiDirectories` function with correct list of paths as required for e2e tests
- Closes #723 
- Depends on #753
> fix(docker): update location for entrypoint.sh

- solo/src/core/k8.mjs
- pick hasDir and copyTo functionalities of k8 class from `code-cleanup` branch
I picked the changes from an old branch `code-cleanup` that has Nathan's updates. However that branch now triggers a lot of conflicts since `fullstack-network-manager` directory was renamed to `solo`. So this PR is an attempt to recover the key changes in `k8` class.
- Closes #
> fix(cli): enhance file copy function of k8 class based on status code

- charts/fullstack-deployment/Chart.lock
- charts/fullstack-deployment/Chart.yaml
- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/values.yaml
- solo/resources/templates/settings.txt
- solo/src/commands/init.mjs
- solo/src/core/platform_installer.mjs
- solo/test/e2e/core/platform_installer_e2e.test.mjs
- path name was misspelled for HapiApp2.0
- path name was incorrect for event streams
- add _ for bucket path names for consistency
- enable event streaming
- update `resetHapiDirectories` to skip resetting `HapiApp2.0/data/saved` and `HapiApp2.0/data/sats` as those are volume mounted for backup-uploader
- Closes #
> fix: correct path names for volumes and upgrade minio

- charts/fullstack-deployment/templates/secrets/uploder-mirror-secrets.yaml
- charts/fullstack-deployment/values.yaml
- empty the mirror node importers address book value
- default the hedera-mirror-node and hedera-explorer to false so that the address book can be updated prior to launching it with a `helm upgrade`
- enhance the `uploader-mirror-secrets.yaml` to not reset the passwords upon a `helm upgrade`
- Closes #761 
- required by https://github.com/hashgraph/solo/pull/52
> fix: set the mirror node importer addressbook to an invalid value to prevent it from starting

- charts/fullstack-deployment/config-files/envoy.yaml
- charts/fullstack-deployment/config-files/haproxy.cfg
- charts/fullstack-deployment/config-files/otel-collector-config.yaml
- charts/fullstack-deployment/templates/services/network-node-svc.yaml
- update service name to match statefulset name for DNS to work correctly
- Closes #814 
- Required by [#96](https://github.com/hashgraph/solo/issues/96)
> fix: service name has to match statefulset name for DNS to work correctly

- charts/fullstack-cluster-setup/values.yaml
- charts/fullstack-deployment/config-files/otel-collector-config.yaml
- charts/fullstack-deployment/templates/configmaps/otel-collector-cm.yaml
- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/templates/telemetry/prometheus-svc-monitor.yaml
- Add labels to metrics
- Allow prometheus operator to discover service-monitors in other namespaces
- Closes #
> fix: add labels to metrics and discover servicemonitors in all namespaces

- charts/fullstack-deployment/values.yaml
- re-enable enable web3 
- Closes #835
> fix: revert change to enable web3 again for mirror node

- charts/fullstack-deployment/templates/services/network-node-svc.yaml
- set network node service as a headless service to support FQDN on GKE in order for config.txt/address book to work correctly with the current solo logic.
- Closes #848
> fix: set network node service as a headless service to support FQDN on GKE

- .github/workflows/zxc-helm-chart-tests.yaml
- charts/fullstack-deployment/config-files/haproxy.cfg
- charts/fullstack-deployment/templates/configmaps/haproxy-cm.yaml
- charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
- charts/fullstack-deployment/templates/services/haproxy-svc.yaml
- update haproxy to use startup probe and not expose and not expose service port 5555
- remove docker prune from `.github/workflows/zxc-helm-chart-tests.yaml`
- update `charts/fullstack-deployment/config-files/haproxy.cfg` to not fail when network-nodeX DNS is not resolvable because it is still starting
- Closes #852
> feat: update haproxy to use startup probe and not expose and not expose service port 5555

- .github/workflows/flow-pull-request-formatting.yaml
- Update source of conventional-pr-title-action to use step-security maintained version
- Closes #863
> ci: Updated source for conventional-pr-title-action

- charts/fullstack-deployment/templates/services/envoy-svc.yaml
- charts/fullstack-deployment/templates/services/haproxy-svc.yaml
- charts/fullstack-deployment/templates/services/network-node-svc.yaml
- Updates service definitions for the network nodes, envoy and haproxy pods.
- Closes #874
> fix: update chart services to use a local external traffic policy

- docker/ubi8-init-java21/entrypoint.sh
- Updates the Java 21 base image entrypoint to use Services modular code by default.
- Closes #881
> feat: update Java 21 base image entrypoint to launch modular Services code

- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/values.yaml
- Adds support for the specification of `extraEnv` on a per node basis on the network node root container. 
- Closes #884
> fix: add support for extraEnv specification on network node root containers

- docker/ubi8-init-java21/network-node.service
- Allows the `JAVA_MAIN_CLASS` and `JAVA_CLASS_PATH` environment variables to be passed to `entrypoint.sh` script when started via systemd.
- Closes #888
> fix: allow entry point supported environment variables to be passed via systemd

- charts/fullstack-deployment/config-files/haproxy.cfg
- charts/fullstack-deployment/templates/_helpers.tpl
- charts/fullstack-deployment/templates/configmaps/haproxy-cm.yaml
- charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
- charts/fullstack-deployment/templates/secrets/haproxy-secrets.yaml
- Created template function to create random proxy user name and password if do not exist
- Use haproxy user name and password as global values so they can be used in both `haproxy-cm.yaml` and `haproxy-deployment.yaml`
- Closes #854
> ci: create random user name and password for haproxy

- charts/fullstack-deployment/Chart.lock
- charts/fullstack-deployment/Chart.yaml
- charts/fullstack-deployment/values.yaml
- Increase mirror node version number
- Enable redis container since it is needed for importer
- Closes #939
> ci: increase mirror chart version

- .github/workflows/flow-deploy-release-artifact.yaml
This PR migrates the `helm-gh-pages` action to the step-security maintained version
- Closes #929
> chore: migrate helm-gh-pages to step-security maintained version

- charts/fullstack-deployment/Chart.lock
- charts/fullstack-deployment/Chart.yaml
- Upgrade Mirror node subchart to v0.110.1
- Closes #950
> fix: upgrade to mirror node to v0.110.1

- .github/workflows/flow-deploy-release-artifact.yaml
- .github/workflows/flow-pull-request-formatting.yaml
- .github/workflows/zxc-code-analysis.yaml
- .github/workflows/zxc-compile-code.yaml
- .github/workflows/zxc-helm-chart-tests.yaml
- .github/workflows/zxc-release-maven-central.yaml
- .github/workflows/zxf-snyk-monitor.yaml
- Updates workflows to use latitude.sh based runners
- Closes #953
> ci: update workflows to use latitude.sh based runners

- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- for the FST charts separate the secrets for the gossip keys for each node
- required by: https://github.com/hashgraph/solo/issues/135
> feat: separate the secrets for the gossip keys for each node

- charts/fullstack-deployment/Chart.yaml
- bump mirror node in FST helm chart to 0.111.1
- required by https://github.com/hashgraph/solo/pull/518
> fix: bump mirror node in FST helm chart to 0.111.1

- charts/fullstack-deployment/values.yaml
Updates the chart values in `fullstack-development` to enable a Pinger service in the Mirror Node Monitor pod.
- Closes #958
> feat: add Pinger config

- charts/fullstack-deployment/templates/network-node-statefulset.yaml
This reverts commit bf1f9c1ef6a58f1d3ec1719b022a15408b65db0f.
- reverts https://github.com/hashgraph/full-stack-testing/issues/818, this will not work the way we planned. We now intend to hit the prometheus metrics endpoint directly on the Solo side.
- Closes #966
> fix: reverts network node liveness probe hitting prometheus metrics endpoint

- .github/workflows/support/ci_test.sh
- charts/fullstack-deployment/Chart.lock
- charts/fullstack-deployment/templates/network-node-statefulset.yaml
- charts/fullstack-deployment/tests/test_basic_deployment.bats
- feat: update Helm charts to handle Hedera Docker container deterministic image
- Relates to https://github.com/hashgraph/solo/issues/341
> feat: update Helm charts to handle Hedera Docker container deterministic image
