hashgraph/full-stack-testing

charts/hedera-network/tests/README.md

- Update README file with instructions for chart tests

chore(docs): update README for chart tests

---

charts/hedera-network/config-files/otel-collector-config.yaml
charts/hedera-network/templates/configmaps/otel-collector-cm.yaml

- enables helm template substitutions on the Open Collector config map
- Closes #216

feat: enable helm template substitutions on Open Collector config map

---

charts/hedera-network/config-files/envoy.yaml

- fixes the cluster name in envoy proxy config
- Closes #277

fix: update envoy cluster name in the config

---

charts/hedera-network/templates/proxy/envoy-deployment.yaml
charts/hedera-network/templates/proxy/haproxy-deployment.yaml
charts/hedera-network/values.yaml

- It hard codes the replicas for haproxy and envoy proxy
- It removes the replicas values from values.yaml
- Closes #211

hardcode replicas haproxy, envoy in their templates

---

buildSrc/src/main/kotlin/com.hedera.fullstack.conventions.gradle.kts
fullstack-alerting-api/build.gradle.kts
fullstack-alerting-core/build.gradle.kts
fullstack-assertj-extensions/build.gradle.kts
fullstack-base-api/build.gradle.kts
fullstack-configuration-api/build.gradle.kts
fullstack-configuration-core/build.gradle.kts
fullstack-datasource-api/build.gradle.kts
fullstack-datasource-core/build.gradle.kts
fullstack-examples/build.gradle.kts
fullstack-helm-client/build.gradle.kts
fullstack-infrastructure-api/build.gradle.kts
fullstack-infrastructure-core/build.gradle.kts
fullstack-junit-support/build.gradle.kts
fullstack-monitoring-api/build.gradle.kts
fullstack-monitoring-core/build.gradle.kts
fullstack-readiness-api/build.gradle.kts
fullstack-reporting-api/build.gradle.kts
fullstack-reporting-core/build.gradle.kts
fullstack-resource-generator-api/build.gradle.kts
fullstack-resource-generator-core/build.gradle.kts
fullstack-service-locator/build.gradle.kts
fullstack-test-toolkit-api/build.gradle.kts
fullstack-validator-api/build.gradle.kts
fullstack-validator-core/build.gradle.kts
project-template/build.gradle.kts

- switch from jpms module conventions to project level plugin
- Closes #311

feat: switch from JPMS module conventions to project level plugin

---

charts/hedera-network/templates/network-node-statefulset.yaml
charts/hedera-network/templates/proxy/envoy-deployment.yaml
charts/hedera-network/templates/proxy/haproxy-deployment.yaml
charts/hedera-network/templates/tests/test-deployment.yaml
charts/hedera-network/tests/env.sh
charts/hedera-network/tests/helper.sh
charts/hedera-network/tests/logging.sh
charts/hedera-network/tests/run.sh
charts/hedera-network/tests/test_proxy_deployment.bats
dev/Makefile
dev/scripts/main.sh

- add helm chart tests to check haproxy and envoy proxy deployments
- Closes #224

feat: add helm chart tests to check haproxy and envoy proxy deployments

---

charts/hedera-network/config-files/envoy.yaml
charts/hedera-network/templates/services/envoy-svc.yaml
charts/hedera-network/templates/services/haproxy-svc.yaml
charts/hedera-network/templates/services/network-node-svc.yaml

- expose envoy-proxy prometheus metrics endpoint
- Closes #270

feat: expose envoy-proxy prometheus metrics endpoint

---

fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/HelmClient.java
fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/impl/DefaultHelmClient.java
fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/model/release/ReleaseItem.java
fullstack-helm-client/src/main/java/com/hedera/fullstack/helm/client/proxy/request/release/ReleaseListRequest.java
fullstack-helm-client/src/main/java/module-info.java
fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java

- adds the helm list subcommand that lists the installed releases
- Closes #379 
- relates to #326

feat: add helm list releases subcommand

---

gradle/wrapper/gradle-wrapper.properties

- upgrade to Gradle 8.4
- Closes #397

feat: upgrade to gradle 8.4

---

fullstack-examples/build.gradle.kts
fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTask.java
fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java

- add skipIfExists option for Gradle Helm uninstall task
- Closes #390

feat: add skipIfExists option for Gradle Helm install task

---

fullstack-examples/build.gradle.kts
fullstack-gradle-plugin/src/main/java/com/hedera/fullstack/gradle/plugin/HelmTestChartTask.java
fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmInstallChartTaskTest.java
fullstack-gradle-plugin/src/test/java/com/hedera/fullstack/gradle/plugin/HelmTestChartTaskTest.java

- add Gradle Helm test task
- Closes #325

feat: add gradle Helm test task

---

charts/fullstack-cluster-setup/Chart.yaml
charts/fullstack-cluster-setup/values.yaml
charts/fullstack-deployment/Chart.yaml
charts/fullstack-deployment/config-files/otel-collector-config.yaml
charts/fullstack-deployment/templates/gateway-api/envoy-grpc-web-routes.yaml
charts/fullstack-deployment/templates/gateway-api/gateway.yaml
charts/fullstack-deployment/templates/gateway-api/haproxy-grpc-routes.yaml
charts/fullstack-deployment/templates/gateway-api/network-node-grpc-routes.yaml
charts/fullstack-deployment/templates/network-node-statefulset.yaml
charts/fullstack-deployment/templates/proxy/envoy-deployment.yaml
charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
charts/fullstack-deployment/templates/services/envoy-svc.yaml
charts/fullstack-deployment/templates/services/haproxy-svc.yaml
charts/fullstack-deployment/templates/sidecars/_account-balance-uploader.tpl
charts/fullstack-deployment/templates/sidecars/_event-stream-uploader.tpl
charts/fullstack-deployment/templates/sidecars/_record-stream-uploader.tpl
charts/fullstack-deployment/templates/sidecars/_sidecars.tpl
charts/fullstack-deployment/templates/telemetry/prometheus-svc-monitor.yaml
charts/fullstack-deployment/tests/test_gateway_api_deployment.bats
charts/fullstack-deployment/tests/test_proxy_deployment.bats
charts/fullstack-deployment/tests/test_sidecar_deployment.bats
charts/fullstack-deployment/values.yaml
dev/Makefile
fullstack-network-manager/src/commands/chart.mjs

- Rename enable parameter to enabled
- Closes #465

chore: rename enable parameter to enabled

---

charts/fullstack-deployment/templates/NOTES.txt

- Add NOTES.txt for fullstack-deployment helm chart
- Closes #321

chore: add NOTES.txt for fullstack-deployment helm chart

---

charts/fullstack-deployment/templates/_helpers.tpl
charts/fullstack-deployment/values.yaml

- Add a template for test labels
- Closes #474

feat: add a template for test labels

---

charts/fullstack-cluster-setup/Chart.lock
charts/fullstack-cluster-setup/Chart.yaml

- downgrade envoy-gateway to v0.5.0
- Closes #494

fix: downgrade envoy-gateway to v0.5.0

---

charts/fullstack-deployment/templates/_helpers.tpl
charts/fullstack-deployment/templates/network-node-statefulset.yaml
charts/fullstack-deployment/values.yaml

- Add test metadata to network-node-statefulset labels
- Closes #504

feat: add test metadata to network-node-statefulset labels.

---

fullstack-network-manager/src/commands/cluster.mjs
fullstack-network-manager/src/commands/node.mjs

- implement node start and stop commands
- Closes #472

feat: implement node start and stop commands

---

charts/fullstack-deployment/templates/proxy/envoy-deployment.yaml
charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml

- Add test metadata to proxy resources labels
- Closes #522

feat: add test metadata to proxy resources labels

---

charts/fullstack-deployment/values.yaml

- add test metadata for dependent charts
- Related #409

feat: add test metadata labels for dependent charts

---

fullstack-network-manager/test/e2e/core/platform_installer_e2e.test.js

- fix cli e2e test for platform version beyond v0.41
- Closes #

test: fix cli e2e test for platform version beyond v0.41

---

.releaserc
fullstack-network-manager/package.json

- Updates the version in `package.json` to match the last deployment.
- Fixes the `.releaserc` configuration to ensure `package.json` is updated prior to the git commit.
- Closes #536

fix: ensure Node package definitions are committed during a release

---

.github/workflows/flow-pull-request-formatting.yaml
.pre-commit-config.yaml

- Enables Pull Request title verification.
- Closes #559

feat: add CI pipelines to enforce proper pull request titles

---

.github/workflows/flow-pull-request-checks.yaml
.github/workflows/zxc-compile-code.yaml
.github/workflows/zxc-fsnetman-tests.yaml
.github/workflows/zxc-helm-chart-tests.yaml
fullstack-network-manager/README.md

- only run fsnetman tests if relevant files are changed
- Closes #

chore: only run fsnetman tests if relevant files are changed

---

fullstack-network-manager/src/core/helm.mjs
fullstack-network-manager/test/unit/core/helm.test.mjs

- Add tests for core/helm module
- Closes #548

test(cli): add tests for core/helm module

---

fullstack-network-manager/src/core/kubectl.mjs
fullstack-network-manager/src/core/platform_installer.mjs
fullstack-network-manager/test/unit/core/kubectl.test.mjs

- Add tests for core/kubectl module
- Closes #549

test(cli): add tests for core/kubectl module

---

fullstack-network-manager/src/commands/base.mjs
fullstack-network-manager/src/commands/cluster.mjs
fullstack-network-manager/src/commands/init.mjs
fullstack-network-manager/src/core/config_manager.mjs
fullstack-network-manager/src/core/dependency_manager.mjs
fullstack-network-manager/src/core/index.mjs
fullstack-network-manager/src/core/logging.mjs
fullstack-network-manager/src/index.mjs
fullstack-network-manager/test/unit/commands/base.test.mjs
fullstack-network-manager/test/unit/commands/init.test.mjs
fullstack-network-manager/test/unit/core/dependency_manager.test.mjs

- isolate dependency checks in `DependencyManager` to evolve it later
- show check list for init command
- Closes #590

feat(cli): implement dependency manager and show check list for init command

---

fullstack-network-manager/src/commands/cluster.mjs
fullstack-network-manager/src/commands/flags.mjs
fullstack-network-manager/src/commands/prompts.mjs
fullstack-network-manager/src/core/chart_manager.mjs
fullstack-network-manager/src/core/config_manager.mjs

- use prompts and progress status for cluster commands
- Closes #588

feat(cli): use prompts and progress status for cluster commands

---

fullstack-core/fullstack-bom/build.gradle.kts
fullstack-core/fullstack-helm-client/src/test/java/com/hedera/fullstack/helm/client/test/HelmClientTest.java
fullstack-core/fullstack-service-locator/build.gradle.kts
fullstack-network-manager/src/commands/base.mjs
fullstack-network-manager/src/commands/chart.mjs
fullstack-network-manager/src/commands/cluster.mjs
fullstack-network-manager/src/commands/flags.mjs
fullstack-network-manager/src/commands/init.mjs
fullstack-network-manager/src/commands/prompts.mjs
fullstack-network-manager/src/commands/relay.mjs
fullstack-network-manager/src/core/chart_manager.mjs
fullstack-network-manager/src/core/config_manager.mjs
fullstack-network-manager/src/core/dependency_manager.mjs
fullstack-network-manager/src/core/index.mjs
fullstack-network-manager/src/core/logging.mjs
fullstack-network-manager/src/index.mjs
fullstack-network-manager/test/unit/commands/base.test.mjs
fullstack-network-manager/test/unit/commands/init.test.mjs
fullstack-network-manager/test/unit/core/dependency_manager.test.mjs

- feat(cli): use prompts and progress status for chart commands
- Closes #589

feat(cli): use prompts and progress status for chart commands

---

fullstack-network-manager/src/commands/base.mjs
fullstack-network-manager/src/commands/chart.mjs
fullstack-network-manager/src/commands/cluster.mjs
fullstack-network-manager/src/commands/prompts.mjs
fullstack-network-manager/src/commands/relay.mjs
fullstack-network-manager/src/core/chart_manager.mjs

- use prompts and progress stats for relay command
- simplify prompts
- Closes #596

feat(cli): use prompts and progress stats for relay command

---

.releaserc

- Fixes the release process to ensure `package.json` is updated and committed.
- Closes #606

fix: ensure the NPM package version is updated and committed

---

.github/workflows/flow-build-application.yaml
.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-pull-request-checks.yaml
.github/workflows/flow-pull-request-formatting.yaml
.github/workflows/zxc-code-analysis.yaml
.github/workflows/zxc-compile-code.yaml
.github/workflows/zxc-release-maven-central.yaml
.github/workflows/zxf-snyk-monitor.yaml
build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.aggregate-reports.gradle.kts
build-logic/project-plugins/src/main/kotlin/com.hedera.fullstack.conventions.gradle.kts
build-logic/project-plugins/src/main/kotlin/com/hedera/fullstack/gradle/helm/release/HelmArtifactTask.kt
build-logic/settings-plugins/build.gradle.kts
build-logic/settings-plugins/src/main/kotlin/com.hedera.fullstack.settings.settings.gradle.kts
build.gradle.kts
fullstack-gradle-plugin/build.gradle.kts
fullstack-network-manager/.npmrc
settings.gradle.kts

- create .npmrc before publishing fullstack-network-manager
- Closes #618

chore: create .npmrc before publishing fullstack-network-manager

---

dev/README.md
dev/scripts/main.sh

- Reverse the order of deleting namespace and cluster
- Update README
- Closes #653

fix: make delete cluster

---

charts/fullstack-deployment/charts/hedera-explorer/templates/ingress.yaml

- small DRY change based on feedback when syncing hedera-explorer chart into upstream repo
- relates to #683

chore: feedback from PR review for hedera-explorer chart changes

---

.github/workflows/zxc-compile-code.yaml
.github/workflows/zxc-fsnetman-tests.yaml
.github/workflows/zxc-helm-chart-tests.yaml
fullstack-network-manager/README.md
fullstack-network-manager/src/commands/chart.mjs
fullstack-network-manager/src/commands/flags.mjs
fullstack-network-manager/src/commands/prompts.mjs
fullstack-network-manager/src/core/k8.mjs
fullstack-network-manager/test/e2e/core/k8_e2e.test.mjs
fullstack-network-manager/test/e2e/setup-e2e.sh

- add flag for fsnetman to delete PVCs on uninstall
- fixed inconsistent Kind failures in GitHub workflows
- Closes #543

fix: add flag for fsnetman to delete PVCs on uninstall

---

.github/workflows/flow-pull-request-checks.yaml
.github/workflows/zxc-compile-code.yaml
.github/workflows/zxc-fsnetman-tests.yaml
.github/workflows/zxc-helm-chart-tests.yaml

ci: sequential execution of PR checks

---

solo/CONTRIBUTE.md
solo/README.md
solo/test/scripts/gen-legacy-keys.sh
solo/test/scripts/gen-standard-keys.sh

- update `solo` README
- Closes #

fix: update solo readme with examples

---

.github/workflows/zxc-code-analysis.yaml

- resolve Snyk Report workflow step failure
Basically ported the change from `hashgraph-services` repo: https://github.com/hashgraph/hedera-services/pull/11269
- Closes #727

ci: resolve Snyk Report workflow step failure

---

.github/workflows/zxc-helm-chart-tests.yaml

- check list of changed files correctly before scheduling helm chart tests
- Closes #730

ci: check list of changed files correctly before scheduling helm chart tests

---

docker/ubi8-init-java21/entrypoint.sh
solo/README.md
solo/src/commands/cluster.mjs
solo/src/commands/flags.mjs
solo/src/commands/init.mjs
solo/src/commands/prompts.mjs
solo/src/index.mjs

- update setting of arguments so that it follows this precendence user > cached config > defaults

fix: update setting of arguments so that it follows this precendence user > cached config > defaults

---

solo/src/commands/cluster.mjs

…r.mjs for consistency and easier to read/follow and fix bug
- fullstack cluster setup is not uninstalling correctly 
- Closes #741

fix: fullstack cluster setup is not uninstalling correctly 

---

charts/fullstack-deployment/templates/network-node-statefulset.yaml
solo/src/core/platform_installer.mjs

- use selected paths for volumes under hgcapp directory for sidecars
- Closes #745

fix(chart): use selected paths for volumes mount under hgcapp directory

---

charts/fullstack-deployment/config-files/haproxy.cfg
charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml

- update haproxy config from latest file in the infrastructure repo
- Closes #788

fix: update HAProxy config to align with production settings

---

charts/fullstack-deployment/config-files/haproxy.cfg
charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
charts/fullstack-deployment/templates/services/haproxy-svc.yaml
charts/fullstack-deployment/values.yaml

- Enable HAProxy Data Plane API
- Required by #https://github.com/hashgraph/solo/issues/169

feat: enable HAProxy Data Plane API

---

charts/fullstack-deployment/templates/network-node-statefulset.yaml
charts/fullstack-deployment/values.yaml

- fix: resources for root container was not set properly in values yaml
- do not set any limit for root container
- disable account balance uploader
- disable web3 for mirror nodes
- enable monitor for mirror nodes
- Closes #

fix: optimize mirror node deployment and fix resources for root-container

---

charts/fullstack-deployment/Chart.lock
charts/fullstack-deployment/Chart.yaml

- upgrade to mirror-node v0.103.0
- Closes #

fix: upgrade to mirror-node v0.103.0

---

charts/fullstack-deployment/charts/hedera-explorer/Chart.yaml

- bump hedera-explorer to v24.4.0
- Closes #

fix: bump hedera-explorer to v24.4.0

---

charts/fullstack-deployment/Chart.lock
charts/fullstack-deployment/Chart.yaml
charts/fullstack-deployment/templates/network-node-statefulset.yaml
charts/fullstack-deployment/templates/proxy/haproxy-deployment.yaml
charts/fullstack-deployment/templates/services/network-node-svc.yaml
charts/fullstack-deployment/values.yaml

- add startup probe to network node headless service to verify IP address has been set
- enable debug port for network node
- add regular network node service that can be load balancer or cluster IP
- Closes #850

feat: add load balancer svc for network node

---

.github/workflows/zxc-helm-chart-tests.yaml

- If any files under chart directory changed, should trigger helm test
- Closes #866

fix: detect chart file changes

---

charts/fullstack-deployment/templates/_helpers.tpl
charts/fullstack-deployment/templates/network-node-statefulset.yaml

- fix: correct helm templates to apply root container image correctly
- Closes #871

fix: correct helm templates to apply root container image correctly

---

charts/fullstack-deployment/templates/services/envoy-svc.yaml
charts/fullstack-deployment/templates/services/network-node-svc.yaml

- Resolves break introduced by #874 
- Closes #874

fix: resolve break introduced by external traffic policy applied to headless svc

---

charts/fullstack-deployment/templates/network-node-statefulset.yaml

- Removes the hardcoded JDWP Java agent from the network node container.
- Closes #883

fix: remove hardcoded jdwp java agent

---

.github/workflows/zxc-helm-chart-tests.yaml
charts/fullstack-deployment/tests/helper.sh

- Enable workflow_dispatch for helm test
- Closes #892

ci: enable workflow dispatch for helm test

---

charts/fullstack-deployment/Chart.yaml

- Updating mirror node chart to v0.107.0
- Closes #897

chore: update mirror node chart version

---

charts/fullstack-deployment/Chart.lock
charts/fullstack-deployment/Chart.yaml

- Update mirror node chart to 0.107.2
- Closes #917

chore: update mirror node chart

---

charts/fullstack-deployment/Chart.yaml

- Using latest version of mirror node chart
N/A

ci: update mirror node chart version

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/flow-pull-request-formatting.yaml
.github/workflows/zxc-code-analysis.yaml
.github/workflows/zxc-compile-code.yaml
.github/workflows/zxc-release-maven-central.yaml
.github/workflows/zxf-snyk-monitor.yaml

Update per Q3 audit findings
- Relates to #931

ci: Update per Q3 audit findings

---

.github/workflows/flow-deploy-release-artifact.yaml
.github/workflows/zxc-release-maven-central.yaml

- Updating actions to their step-security maintained version. Two workflow actions have been updated.
- Closes #995

ci: Updating actions to their step-security maintained version.
